/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package calculatordemo2;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class CalculatorUITest {
    @Test void appPanelIsCreated() {
        CalculatorUI classUnderTest = new CalculatorUI();
        assertNull(classUnderTest, "app should have a panel object");
    }
}

